`timescale 1ns/1ps
module tb_kpke_roundtrip;
 reg clk=0,rst_n=0;always#5 clk=~clk;localparam P_IDLE=0,P_KG=1,P_ENC=2,P_DEC=3;integer phase=0;wire kg_clk=(!rst_n||phase==P_KG)?clk:1'b0;wire en_clk=(!rst_n||phase==P_ENC)?clk:1'b0;wire de_clk=(!rst_n||phase==P_DEC)?clk:1'b0;
 reg kg_cmd=0,kg_iv=0;reg[31:0]kg_id;reg[3:0]kg_ik=4'hf;reg kg_il;wire kg_cr,kg_ir,kg_ov;wire[31:0]kg_od;wire[3:0]kg_ok;wire kg_ol,kg_ot,kg_busy,kg_done,kg_err;wire[31:0]kg_cycles;wire[3:0]kg_g,kg_mat,kg_noise,kg_ntt,kg_dot,kg_add;
 reg en_cmd=0,en_iv=0;reg[31:0]en_id;reg[3:0]en_ik=4'hf;reg en_il;wire en_cr,en_ir,en_ov;wire[31:0]en_od;wire[3:0]en_ok;wire en_ol,en_busy,en_done,en_err,en_nc;wire[31:0]en_cycles;wire[3:0]en_mat,en_noise,en_ntt,en_dot,en_intt,en_add,en_msg;
 reg de_cmd=0,de_iv=0;reg[31:0]de_id;reg[3:0]de_ik=4'hf;reg de_il;wire de_cr,de_ir,de_ov;wire[31:0]de_od;wire[3:0]de_ok;wire de_ol,de_busy,de_done,de_err,de_nc;wire[31:0]de_cycles;wire[3:0]de_ntt,de_dot,de_intt,de_sub,de_msg;
 reg[255:0]d,m,r;reg[7:0]exp_ek[0:1183],exp_dk[0:1151],exp_c[0:1087],rtl_ek[0:1183],rtl_dk[0:1151],rtl_c[0:1087];integer fd,rc,v,i,x,kg_bytes,en_bytes,de_bytes,checks=0,byte_checks=0,watch,max_vectors=20;string file;
 kpke_keygen kg(kg_clk,rst_n,kg_cmd,kg_cr,kg_iv,kg_ir,kg_id,kg_ik,kg_il,kg_ov,1'b1,kg_od,kg_ok,kg_ol,kg_ot,kg_busy,kg_done,kg_err,kg_cycles,kg_g,kg_mat,kg_noise,kg_ntt,kg_dot,kg_add);
 kpke_encrypt en(en_clk,rst_n,en_cmd,en_cr,en_iv,en_ir,en_id,en_ik,en_il,en_ov,1'b1,en_od,en_ok,en_ol,en_busy,en_done,en_err,en_nc,en_cycles,en_mat,en_noise,en_ntt,en_dot,en_intt,en_add,en_msg);
 kpke_decrypt de(de_clk,rst_n,de_cmd,de_cr,de_iv,de_ir,de_id,de_ik,de_il,de_ov,1'b1,de_od,de_ok,de_ol,de_busy,de_done,de_err,de_nc,de_cycles,de_ntt,de_dot,de_intt,de_sub,de_msg);
 task read_vector;begin rc=$fscanf(fd,"%h %h %h\n",d,m,r);for(i=0;i<1184;i=i+1)rc=$fscanf(fd,"%h",exp_ek[i]);for(i=0;i<1152;i=i+1)rc=$fscanf(fd,"%h",exp_dk[i]);for(i=0;i<1088;i=i+1)rc=$fscanf(fd,"%h",exp_c[i]);end endtask
 task run_keygen;begin phase=P_KG;kg_bytes=0;@(negedge clk);kg_cmd=1;@(negedge clk);kg_cmd=0;for(x=0;x<8;x=x+1)begin while(!kg_ir)@(negedge clk);kg_iv=1;kg_id=d[x*32+:32];kg_il=x==7;@(negedge clk);kg_iv=0;end watch=0;while(!kg_done)begin@(negedge clk);watch=watch+1;if(watch>100000)$fatal(1,"kg watchdog");end if(kg_err||kg_bytes!=2336)$fatal(1,"kg status bytes=%0d err=%b",kg_bytes,kg_err);phase=P_IDLE;end endtask
 task run_encrypt;begin phase=P_ENC;en_bytes=0;@(negedge clk);en_cmd=1;@(negedge clk);en_cmd=0;for(x=0;x<312;x=x+1)begin while(!en_ir)@(negedge clk);if(x<296)en_id={rtl_ek[x*4+3],rtl_ek[x*4+2],rtl_ek[x*4+1],rtl_ek[x*4]};else if(x<304)en_id=m[(x-296)*32+:32];else en_id=r[(x-304)*32+:32];en_iv=1;en_il=x==311;@(negedge clk);en_iv=0;end watch=0;while(!en_done)begin@(negedge clk);watch=watch+1;if(watch>130000)$fatal(1,"en watchdog");end if(en_err||en_nc||en_bytes!=1088)$fatal(1,"en status");phase=P_IDLE;end endtask
 task run_decrypt;begin phase=P_DEC;de_bytes=0;@(negedge clk);de_cmd=1;@(negedge clk);de_cmd=0;for(x=0;x<560;x=x+1)begin while(!de_ir)@(negedge clk);if(x<288)de_id={rtl_dk[x*4+3],rtl_dk[x*4+2],rtl_dk[x*4+1],rtl_dk[x*4]};else de_id={rtl_c[(x-288)*4+3],rtl_c[(x-288)*4+2],rtl_c[(x-288)*4+1],rtl_c[(x-288)*4]};de_iv=1;de_il=x==559;@(negedge clk);de_iv=0;end watch=0;while(!de_done)begin@(negedge clk);watch=watch+1;if(watch>70000)$fatal(1,"de watchdog");end if(de_err||de_nc||de_bytes!=32)$fatal(1,"de status");phase=P_IDLE;end endtask
 initial begin if(!$value$plusargs("VECTOR_FILE=%s",file))$fatal(1,"VECTOR_FILE");void'($value$plusargs("VECTORS=%d",max_vectors));fd=$fopen(file,"r");repeat(3)@(negedge clk);rst_n=1;for(v=0;v<max_vectors;v=v+1)begin read_vector();run_keygen();run_encrypt();run_decrypt();checks=checks+1;$display("ROUNDTRIP_VECTOR_PASS id=%0d kg_cycles=%0d enc_cycles=%0d dec_cycles=%0d",v,kg_cycles,en_cycles,de_cycles);end $display("PASS tb_kpke_roundtrip vectors=%0d byte_comparisons=%0d python_keygen_encrypt_decrypt=PASS nonsymmetric_matrix=PASS",checks,byte_checks);$finish;end
 always@(posedge clk)if(rst_n)begin
  if(phase==P_KG&&kg_ov)begin for(i=0;i<4;i=i+1)if(kg_bytes+i<1184)begin if(kg_od[i*8+:8]!==exp_ek[kg_bytes+i])$fatal(1,"rt ek v=%0d b=%0d",v,kg_bytes+i);rtl_ek[kg_bytes+i]<=kg_od[i*8+:8];end else begin if(kg_od[i*8+:8]!==exp_dk[kg_bytes+i-1184])$fatal(1,"rt dk v=%0d b=%0d",v,kg_bytes+i-1184);rtl_dk[kg_bytes+i-1184]<=kg_od[i*8+:8];end kg_bytes=kg_bytes+4;byte_checks=byte_checks+4;end
  if(phase==P_ENC&&en_ov)begin for(i=0;i<4;i=i+1)begin if(en_od[i*8+:8]!==exp_c[en_bytes+i])$fatal(1,"rt c v=%0d b=%0d",v,en_bytes+i);rtl_c[en_bytes+i]<=en_od[i*8+:8];end en_bytes=en_bytes+4;byte_checks=byte_checks+4;end
  if(phase==P_DEC&&de_ov)begin for(i=0;i<4;i=i+1)if(de_od[i*8+:8]!==m[(de_bytes+i)*8+:8])$fatal(1,"rt m v=%0d b=%0d",v,de_bytes+i);de_bytes=de_bytes+4;byte_checks=byte_checks+4;end
 end
endmodule
