`timescale 1ns/1ps
module tb_kpke_decrypt;
 reg clk=0,rst_n=0,cmd_valid=0,in_valid=0,out_ready=1;reg[31:0]in_data;reg[3:0]in_keep;reg in_last;wire cmd_ready,in_ready,out_valid;wire[31:0]out_data;wire[3:0]out_keep;wire out_last,busy,done,error,nc;wire[31:0]cycle_count;wire[3:0]polyvec_ntt_operations,dot_operations,intt_operations,poly_sub_operations,message_operations;
 reg[7:0]exp_dk[0:1151],exp_c[0:1087];reg[11:0]exp_u[0:767],exp_sh[0:767],exp_uh[0:767],exp_vp[0:255],exp_prod[0:255],exp_w[0:255];reg[255:0]exp_msg;
 integer fd,rc,v,i,x,got,max_vectors=20,checks=0,coeff_checks=0,byte_checks=0,cycles,stall_cycle=0;string file;reg held;reg[31:0]hd;reg hl;
 always#5 clk=~clk;kpke_decrypt dut(clk,rst_n,cmd_valid,cmd_ready,in_valid,in_ready,in_data,in_keep,in_last,out_valid,out_ready,out_data,out_keep,out_last,busy,done,error,nc,cycle_count,polyvec_ntt_operations,dot_operations,intt_operations,poly_sub_operations,message_operations);
 task read_vector;begin for(i=0;i<1152;i=i+1)rc=$fscanf(fd,"%h",exp_dk[i]);for(i=0;i<1088;i=i+1)rc=$fscanf(fd,"%h",exp_c[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_u[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_sh[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_uh[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_vp[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_prod[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_w[i]);rc=$fscanf(fd,"%h\n",exp_msg);end endtask
 task run_vector;begin @(negedge clk);cmd_valid=1;@(negedge clk);cmd_valid=0;for(x=0;x<560;x=x+1)begin while(!in_ready)@(negedge clk);if(x<288)in_data={exp_dk[x*4+3],exp_dk[x*4+2],exp_dk[x*4+1],exp_dk[x*4]};else in_data={exp_c[(x-288)*4+3],exp_c[(x-288)*4+2],exp_c[(x-288)*4+1],exp_c[(x-288)*4]};in_valid=1;in_keep=4'hf;in_last=x==559;@(negedge clk);in_valid=0;end got=0;cycles=0;while(!done)begin @(negedge clk);cycles=cycles+1;if(cycles>70000)$fatal(1,"watchdog v=%0d state=%0d elem=%0d idx=%0d",v,dut.state,dut.elem,dut.idx);end if(error||nc||got!=32)$fatal(1,"status v=%0d got=%0d err=%b nc=%b",v,got,error,nc);if(polyvec_ntt_operations!=1||dot_operations!=1||intt_operations!=1||poly_sub_operations!=1||message_operations!=1)$fatal(1,"counts %0d %0d %0d %0d %0d",polyvec_ntt_operations,dot_operations,intt_operations,poly_sub_operations,message_operations);
  for(i=0;i<768;i=i+1)begin if(dut.u[i]!==exp_u[i])$fatal(1,"u v=%0d p=%0d i=%0d",v,i/256,i%256);if(dut.s_hat[i]!==exp_sh[i])$fatal(1,"sh v=%0d p=%0d i=%0d",v,i/256,i%256);if(dut.u_hat[i]!==exp_uh[i])$fatal(1,"uh v=%0d p=%0d i=%0d",v,i/256,i%256);coeff_checks=coeff_checks+3;end for(i=0;i<256;i=i+1)begin if(dut.vp[i]!==exp_vp[i]||dut.product[i]!==exp_prod[i]||dut.wpoly[i]!==exp_w[i])$fatal(1,"poly v=%0d i=%0d vp=%0d/%0d prod=%0d/%0d w=%0d/%0d",v,i,dut.vp[i],exp_vp[i],dut.product[i],exp_prod[i],dut.wpoly[i],exp_w[i]);coeff_checks=coeff_checks+3;end checks=checks+1;byte_checks=byte_checks+32;$display("DECRYPT_VECTOR_PASS id=%0d cycles=%0d",v,cycle_count);end endtask
 initial begin if(!$value$plusargs("VECTOR_FILE=%s",file))$fatal(1,"VECTOR_FILE");void'($value$plusargs("VECTORS=%d",max_vectors));fd=$fopen(file,"r");repeat(3)@(negedge clk);rst_n=1;for(v=0;v<max_vectors;v=v+1)begin read_vector();run_vector();end $display("PASS tb_kpke_decrypt vectors=%0d coefficient_comparisons=%0d byte_comparisons=%0d last_cycles=%0d operation_counts=PASS backpressure=PASS",checks,coeff_checks,byte_checks,cycle_count);$finish;end
 always@(negedge clk)if(rst_n)begin stall_cycle=stall_cycle+1;out_ready=(stall_cycle%9)!=4;end always@(posedge clk)if(!rst_n)held<=0;else begin if(held&&(!out_valid||out_data!==hd||out_last!==hl))$fatal(1,"stall");held=out_valid&&!out_ready;if(out_valid&&!out_ready)begin hd=out_data;hl=out_last;end if(out_valid&&out_ready)begin if(out_keep!=4'hf||out_last!==(got==28))$fatal(1,"meta");for(i=0;i<4;i=i+1)if(out_data[i*8+:8]!==exp_msg[(got+i)*8+:8])$fatal(1,"m v=%0d byte=%0d exp=%02x got=%02x",v,got+i,exp_msg[(got+i)*8+:8],out_data[i*8+:8]);got=got+4;end end
endmodule
