`timescale 1ns/1ps
module tb_kpke_encrypt;
 reg clk=0,rst_n=0,cmd_valid=0,in_valid=0,out_ready=1;reg[31:0]in_data;reg[3:0]in_keep;reg in_last;
 wire cmd_ready,in_ready,out_valid;wire[31:0]out_data;wire[3:0]out_keep;wire out_last,busy,done,error,nc;wire[31:0]cycle_count;wire[3:0]sample_ntt_operations,noise_operations,polyvec_ntt_operations,dot_operations,intt_operations,poly_add_operations,message_operations;
 reg[7:0]exp_ek[0:1183],exp_c[0:1087];reg[255:0]msg,randomness,exp_rho;reg[11:0]exp_t[0:767],exp_y[0:767],exp_e1[0:767],exp_yh[0:767],exp_u[0:767],exp_e2[0:255],exp_mu[0:255],exp_v[0:255];
 integer fd,rc,v,i,w,got,cycles,max_vectors=20,checks=0,coeff_checks=0,byte_checks=0,stall_cycle=0;string file;reg held;reg[31:0]hd;reg hl;
 always#5 clk=~clk;
 kpke_encrypt dut(clk,rst_n,cmd_valid,cmd_ready,in_valid,in_ready,in_data,in_keep,in_last,out_valid,out_ready,out_data,out_keep,out_last,busy,done,error,nc,cycle_count,sample_ntt_operations,noise_operations,polyvec_ntt_operations,dot_operations,intt_operations,poly_add_operations,message_operations);
 task read_vector;begin for(i=0;i<1184;i=i+1)rc=$fscanf(fd,"%h",exp_ek[i]);rc=$fscanf(fd,"%h %h %h\n",msg,randomness,exp_rho);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_t[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_y[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_e1[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_yh[i]);for(i=0;i<768;i=i+1)rc=$fscanf(fd,"%h",exp_u[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_e2[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_mu[i]);for(i=0;i<256;i=i+1)rc=$fscanf(fd,"%h",exp_v[i]);for(i=0;i<1088;i=i+1)rc=$fscanf(fd,"%h",exp_c[i]);end endtask
 task run_vector;begin @(negedge clk);cmd_valid=1;@(negedge clk);cmd_valid=0;for(w=0;w<312;w=w+1)begin while(!in_ready)@(negedge clk);if(w<296)in_data={exp_ek[w*4+3],exp_ek[w*4+2],exp_ek[w*4+1],exp_ek[w*4]};else if(w<304)in_data=msg[(w-296)*32+:32];else in_data=randomness[(w-304)*32+:32];in_valid=1;in_keep=4'hf;in_last=w==311;@(negedge clk);in_valid=0;end got=0;cycles=0;while(!done)begin @(negedge clk);cycles=cycles+1;if(cycles>150000)$fatal(1,"watchdog v=%0d state=%0d row=%0d elem=%0d idx=%0d vb=%b second=%b",v,dut.state,dut.row,dut.elem,dut.idx,dut.vbranch,dut.add_second);end if(error||nc||got!=1088)$fatal(1,"status v=%0d bytes=%0d error=%b nc=%b",v,got,error,nc);if(sample_ntt_operations!=9||noise_operations!=7||polyvec_ntt_operations!=1||dot_operations!=4||intt_operations!=4||poly_add_operations!=5||message_operations!=1)$fatal(1,"counts mat=%0d noise=%0d ntt=%0d dot=%0d intt=%0d add=%0d msg=%0d",sample_ntt_operations,noise_operations,polyvec_ntt_operations,dot_operations,intt_operations,poly_add_operations,message_operations);
  for(i=0;i<32;i=i+1)if(dut.rho[i]!==exp_rho[i*8+:8])$fatal(1,"rho v=%0d i=%0d",v,i);
  for(i=0;i<768;i=i+1)begin if(dut.t_hat[i]!==exp_t[i])$fatal(1,"t v=%0d p=%0d i=%0d exp=%0d got=%0d",v,i/256,i%256,exp_t[i],dut.t_hat[i]);if(dut.y[i]!==exp_y[i])$fatal(1,"y v=%0d p=%0d i=%0d",v,i/256,i%256);if(dut.e1[i]!==exp_e1[i])$fatal(1,"e1 v=%0d p=%0d i=%0d",v,i/256,i%256);if(dut.y_hat[i]!==exp_yh[i])$fatal(1,"yh v=%0d p=%0d i=%0d",v,i/256,i%256);if(dut.u[i]!==exp_u[i])$fatal(1,"u v=%0d p=%0d i=%0d exp=%0d got=%0d",v,i/256,i%256,exp_u[i],dut.u[i]);coeff_checks=coeff_checks+5;end
  for(i=0;i<256;i=i+1)begin if(dut.e2[i]!==exp_e2[i]||dut.mu[i]!==exp_mu[i]||dut.v[i]!==exp_v[i])$fatal(1,"poly v=%0d i=%0d e2=%0d/%0d mu=%0d/%0d vv=%0d/%0d",v,i,dut.e2[i],exp_e2[i],dut.mu[i],exp_mu[i],dut.v[i],exp_v[i]);coeff_checks=coeff_checks+3;end checks=checks+1;byte_checks=byte_checks+1120;$display("ENCRYPT_VECTOR_PASS id=%0d cycles=%0d",v,cycle_count);end endtask
 initial begin if(!$value$plusargs("VECTOR_FILE=%s",file))$fatal(1,"VECTOR_FILE");void'($value$plusargs("VECTORS=%d",max_vectors));fd=$fopen(file,"r");repeat(3)@(negedge clk);rst_n=1;for(v=0;v<max_vectors;v=v+1)begin read_vector();run_vector();end $display("PASS tb_kpke_encrypt vectors=%0d coefficient_comparisons=%0d byte_comparisons=%0d last_cycles=%0d transpose_counts=PASS operation_counts=PASS backpressure=PASS",checks,coeff_checks,byte_checks,cycle_count);$finish;end
 always@(negedge clk)if(rst_n)begin stall_cycle=stall_cycle+1;out_ready=(stall_cycle%13)!=7;end
 always@(posedge clk)if(!rst_n)held<=0;else begin if(held&&(!out_valid||out_data!==hd||out_last!==hl))$fatal(1,"stall");held=out_valid&&!out_ready;if(out_valid&&!out_ready)begin hd=out_data;hl=out_last;end if(out_valid&&out_ready)begin if(out_keep!=4'hf||out_last!==(got==1084))$fatal(1,"meta off=%0d",got);for(i=0;i<4;i=i+1)if(out_data[i*8+:8]!==exp_c[got+i])$fatal(1,"c v=%0d byte=%0d exp=%02x got=%02x state=%0d",v,got+i,exp_c[got+i],out_data[i*8+:8],dut.state);got=got+4;end end
endmodule
