`timescale 1ns/1ps
module tb_m5_cycle_accounting;
reg clk=0,rst_n=0;always #5 clk=~clk;
reg hcmd=0;wire hcr;reg[1:0]hmode;reg[31:0]hmlen,holen;reg hiv=0;wire hir;reg[31:0]hid=0;reg[3:0]hik=0;reg hil=0;wire hov;reg hor=1;wire[31:0]hod;wire[3:0]hok;wire hol,hbusy,hdone,herror;
reg pstart=0;wire pready,pov;reg por=1;wire[31:0]pod;wire[3:0]pok;wire pol,pbusy,pdone,perror;reg[1:0]peta;
reg xinit=0;wire xiready,xsr,xov,xctx,xbusy,xdone,xerror;reg xsv=0,xout_ready=1;reg[31:0]xlen;wire[31:0]xod;wire[3:0]xok;wire xol;
keccak_hash_stream h(.clk(clk),.rst_n(rst_n),.cmd_valid(hcmd),.cmd_ready(hcr),.mode(hmode),.msg_len_bytes(hmlen),.out_len_bytes(holen),.in_valid(hiv),.in_ready(hir),.in_data(hid),.in_keep(hik),.in_last(hil),.out_valid(hov),.out_ready(hor),.out_data(hod),.out_keep(hok),.out_last(hol),.busy(hbusy),.done(hdone),.error(herror));
mlkem_prf p(.clk(clk),.rst_n(rst_n),.start(pstart),.ready(pready),.seed(256'h0),.nonce(8'h0),.eta(peta),.out_valid(pov),.out_ready(por),.out_data(pod),.out_keep(pok),.out_last(pol),.busy(pbusy),.done(pdone),.error(perror));
mlkem_xof x(.clk(clk),.rst_n(rst_n),.init_valid(xinit),.init_ready(xiready),.seed(256'h0),.index0(0),.index1(0),.use_generic_input(0),.generic_input(0),.squeeze_req_valid(xsv),.squeeze_req_ready(xsr),.squeeze_len_bytes(xlen),.out_valid(xov),.out_ready(xout_ready),.out_data(xod),.out_keep(xok),.out_last(xol),.context_valid(xctx),.busy(xbusy),.done(xdone),.error(xerror));
task reset;begin @(negedge clk);rst_n=0;hcmd=0;hiv=0;pstart=0;xinit=0;xsv=0;@(posedge clk);@(negedge clk);rst_n=1;end endtask
task hash_case;input integer md;input integer ml;input integer ol;integer pos,n,j,t0,tf,tl,wd;begin while(!hcr)@(posedge clk);@(negedge clk);hmode=md;hmlen=ml;holen=ol;hcmd=1;@(posedge clk);t0=$time;@(negedge clk);hcmd=0;pos=0;while(pos<ml)begin n=(ml-pos>=4)?4:ml-pos;hid=0;for(j=0;j<n;j=j+1)hid[8*j+:8]=0;hik=(n==1)?1:(n==2)?3:(n==3)?7:15;hil=(pos+n==ml);hiv=1;while(!hir)@(posedge clk);@(posedge clk);pos=pos+n;@(negedge clk);hiv=0;end tf=-1;wd=0;while(wd<50000)begin @(posedge clk);wd=wd+1;if(hov)begin if(tf<0)tf=$time;if(hol)begin tl=$time;$display("CYCLE_HASH mode=%0d msg=%0d out=%0d first=%0d total=%0d",md,ml,ol,(tf-t0)/10,(tl-t0)/10);wd=50000;end end end @(posedge clk);end endtask
task prf_case;input integer et;integer t0,tf,tl,wd;begin while(!pready)@(posedge clk);@(negedge clk);peta=et;pstart=1;@(posedge clk);t0=$time;@(negedge clk);pstart=0;tf=-1;wd=0;while(wd<50000)begin @(posedge clk);wd=wd+1;if(pov)begin if(tf<0)tf=$time;if(pol)begin tl=$time;$display("CYCLE_PRF eta=%0d first=%0d total=%0d",et,(tf-t0)/10,(tl-t0)/10);wd=50000;end end end @(posedge clk);end endtask
task xof_request;input integer len;integer t0,tf,tl,wd;begin while(!xsr)@(posedge clk);@(negedge clk);xlen=len;xsv=1;@(posedge clk);t0=$time;@(negedge clk);xsv=0;tf=-1;wd=0;while(wd<50000)begin @(posedge clk);wd=wd+1;if(xov)begin if(tf<0)tf=$time;if(xol)begin tl=$time;$display("CYCLE_XOF_REQUEST len=%0d first=%0d total=%0d",len,(tf-t0)/10,(tl-t0)/10);wd=50000;end end end @(posedge clk);end endtask
integer xt0,xta;initial begin reset();hash_case(0,0,32);hash_case(0,136,32);hash_case(0,137,32);hash_case(1,0,64);hash_case(1,72,64);hash_case(2,0,1);hash_case(2,0,168);hash_case(2,0,169);hash_case(2,168,32);hash_case(3,0,32);hash_case(3,33,32);hash_case(3,33,128);hash_case(3,33,192);prf_case(2);prf_case(3);while(!xiready)@(posedge clk);@(negedge clk);xinit=1;@(posedge clk);xt0=$time;@(negedge clk);xinit=0;while(!xctx)@(posedge clk);xta=$time;$display("CYCLE_XOF_INIT_TO_ACTIVE=%0d",(xta-xt0)/10);xof_request(3);xof_request(168);xof_request(171);if(herror||perror||xerror)$fatal(1,"cycle accounting error");$display("PASS tb_m5_cycle_accounting");$finish;end
endmodule
