rtl/arithmetic/barrett_reduce_pipe.v
rtl/arithmetic/mod_add.v
rtl/arithmetic/mod_add_pipe.v
rtl/arithmetic/mod_mul.v
rtl/arithmetic/mod_mul_normal_pipe.v
rtl/arithmetic/mod_mul_pipe.v
rtl/arithmetic/mod_sub.v
rtl/arithmetic/mod_sub_pipe.v
rtl/arithmetic/montgomery_reduce_pipe.v
rtl/arithmetic/reduction.v
rtl/codec/bits_to_bytes_pipe.v
rtl/codec/byte_decode_poly_pipe.v
rtl/codec/byte_encode_poly_pipe.v
rtl/codec/bytes_to_bits_pipe.v
rtl/codec/compress_coeff_pipe.v
rtl/codec/decompress_coeff_pipe.v
rtl/codec/kpke_ciphertext_pack_pipe.v
rtl/codec/kpke_ciphertext_unpack_pipe.v
rtl/codec/kpke_dk_pack_pipe.v
rtl/codec/kpke_dk_unpack_pipe.v
rtl/codec/kpke_ek_pack_pipe.v
rtl/codec/kpke_ek_unpack_pipe.v
rtl/codec/kpke_format_pipe.v
rtl/codec/message_to_poly_pipe.v
rtl/codec/poly_compress_encode_pipe.v
rtl/codec/poly_decode12_pipe.v
rtl/codec/poly_decode_decompress_pipe.v
rtl/codec/poly_encode12_pipe.v
rtl/codec/poly_to_message_pipe.v
rtl/codec/polyvec_codec_pipe.v
rtl/codec/polyvec_compress_encode10_pipe.v
rtl/codec/polyvec_decode12_pipe.v
rtl/codec/polyvec_decode_decompress10_pipe.v
rtl/codec/polyvec_encode12_pipe.v
rtl/control/fixed_latency_delay.v
rtl/control/rv_register_slice.v
rtl/keccak/keccak_f1600_core.v
rtl/keccak/keccak_hash_stream.v
rtl/keccak/keccak_round.v
rtl/keccak/keccak_sponge_ctx.v
rtl/keccak/mlkem_g.v
rtl/keccak/mlkem_h.v
rtl/keccak/mlkem_j.v
rtl/keccak/mlkem_prf.v
rtl/keccak/mlkem_xof.v
rtl/keccak/sha3_256_stream.v
rtl/keccak/sha3_512_stream.v
rtl/keccak/shake128_stream.v
rtl/keccak/shake256_stream.v
rtl/kpke/kpke_decrypt.v
rtl/kpke/kpke_encrypt.v
rtl/kpke/kpke_keygen.v
rtl/kpke/kpke_matrix_row_sampler.v
rtl/kpke/kpke_noise_vector_sampler.v
rtl/memory/ntt_bank_map.v
rtl/memory/ntt_pingpong_banks.v
rtl/memory/poly_buffer.v
rtl/memory/sync_1r1w_ram.v
rtl/mlkem/mlkem768_top.v
rtl/mlkem/mlkem_byte_buffer.v
rtl/mlkem/mlkem_ct_compare_select.v
rtl/mlkem/mlkem_decaps.v
rtl/mlkem/mlkem_decaps_input_check.v
rtl/mlkem/mlkem_decaps_internal.v
rtl/mlkem/mlkem_dk_assemble.v
rtl/mlkem/mlkem_dk_parse.v
rtl/mlkem/mlkem_ek_check.v
rtl/mlkem/mlkem_encaps.v
rtl/mlkem/mlkem_encaps_internal.v
rtl/mlkem/mlkem_keygen.v
rtl/mlkem/mlkem_keygen_internal.v
rtl/mlkem/mlkem_zeroize_controller.v
rtl/ntt/basemul_unit.v
rtl/ntt/butterfly_pipe.v
rtl/ntt/butterfly_unit.v
rtl/ntt/intt_butterfly_pipe.v
rtl/ntt/intt_butterfly_unit.v
rtl/ntt/intt_core.v
rtl/ntt/intt_core_pipe.v
rtl/ntt/intt_scaler_pipe.v
rtl/ntt/intt_scheduler_pipe.v
rtl/ntt/ntt_addr_gen.v
rtl/ntt/ntt_core.v
rtl/ntt/ntt_core_pipe.v
rtl/ntt/ntt_scheduler_pipe.v
rtl/ntt/zetas_rom.v
rtl/poly/basecase_mul_pipe.v
rtl/poly/poly_add.v
rtl/poly/poly_add_pipe.v
rtl/poly/poly_basemul_addr_gen.v
rtl/poly/poly_basemul_montgomery.v
rtl/poly/poly_basemul_pipe.v
rtl/poly/poly_binary_pipe.v
rtl/poly/poly_intt_pipe.v
rtl/poly/poly_ntt_pipe.v
rtl/poly/poly_reduce.v
rtl/poly/poly_reduce_pipe.v
rtl/poly/poly_sub.v
rtl/poly/poly_sub_pipe.v
rtl/poly/poly_transform_pipe.v
rtl/poly/poly_workspace.v
rtl/poly/polyvec_add_pipe.v
rtl/poly/polyvec_basemul_acc_pipe.v
rtl/poly/polyvec_elementwise_pipe.v
rtl/poly/polyvec_intt_pipe.v
rtl/poly/polyvec_ntt_pipe.v
rtl/poly/polyvec_reduce_pipe.v
rtl/poly/polyvec_sub_pipe.v
rtl/poly/polyvec_workspace.v
rtl/sampler/cbd_pair_pipe.v
rtl/sampler/mlkem_noise_sampler.v
rtl/sampler/mlkem_sample_ntt.v
rtl/sampler/sample_ntt_parser.v
rtl/sampler/sample_poly_cbd_pipe.v
